# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0f5b5f224507b37ce5aaafec1d23a1c7f9cf6e0ca9a94549cd062ef8e041c87b627668a500546649ba3c77f1af0bef2bb4801a22ff762df36454f946996c071

test:
  secret_key_base: 45d8ccddf3ab73f8a4b97d2370a08a88ad7377f764fdfcfd351c622fb4fa61e917e3d176b6ae138b3eb413189e2b8e4db41ce3260ff9fdadc73be303586933a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
